module repository{
	interface LibraryInterface{
	string connect(in string message);
	string addItem (in string managerID,in string itemID,in string itemName,in long quantity);
	string removeItem (in string managerID,in string itemID,in long quantity);
	string listItemAvailability (in string managerID);
	string borrowItem (in string userID,in string itemID);
	string findItem (in string userID,in string itemName);
	string returnItem (in string userID,in string itemID);
	string exchangeItem (in string userID,in string newItemID,in string oldItemID);
	string oldBookCheck(in string userID,in string itemID);
	string newBookCheck(in string userID,in string itemID);
	string addToWaitlist(in string userID, in string itemID);
	string serverRequestFind(in string userID, in string itemName);
	long checkBorrowedBooks(in string userID);
	};
};