package repository;


/**
* repository/LibraryInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LibraryInterface.idl
* Friday, 22 March, 2019 10:53:02 PM EDT
*/

public interface LibraryInterfaceOperations 
{
  String connect (String message);
  String addItem (String managerID, String itemID, String itemName, int quantity);
  String removeItem (String managerID, String itemID, int quantity);
  String listItemAvailability (String managerID);
  String borrowItem (String userID, String itemID);
  String findItem (String userID, String itemName);
  String returnItem (String userID, String itemID);
  String exchangeItem (String userID, String newItemID, String oldItemID);
  String oldBookCheck (String userID, String itemID);
  String newBookCheck (String userID, String itemID);
  String addToWaitlist (String userID, String itemID);
  String serverRequestFind (String userID, String itemName);
  int checkBorrowedBooks (String userID);
} // interface LibraryInterfaceOperations
