package repository;


/**
* repository/LibraryInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LibraryInterface.idl
* Friday, 22 March, 2019 10:53:02 PM EDT
*/

public interface LibraryInterface extends LibraryInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LibraryInterface
