package repository;


/**
* repository/LibraryInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LibraryInterface.idl
* Friday, 22 March, 2019 10:53:02 PM EDT
*/

public abstract class LibraryInterfacePOA extends org.omg.PortableServer.Servant
 implements repository.LibraryInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("connect", new java.lang.Integer (0));
    _methods.put ("addItem", new java.lang.Integer (1));
    _methods.put ("removeItem", new java.lang.Integer (2));
    _methods.put ("listItemAvailability", new java.lang.Integer (3));
    _methods.put ("borrowItem", new java.lang.Integer (4));
    _methods.put ("findItem", new java.lang.Integer (5));
    _methods.put ("returnItem", new java.lang.Integer (6));
    _methods.put ("exchangeItem", new java.lang.Integer (7));
    _methods.put ("oldBookCheck", new java.lang.Integer (8));
    _methods.put ("newBookCheck", new java.lang.Integer (9));
    _methods.put ("addToWaitlist", new java.lang.Integer (10));
    _methods.put ("serverRequestFind", new java.lang.Integer (11));
    _methods.put ("checkBorrowedBooks", new java.lang.Integer (12));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // repository/LibraryInterface/connect
       {
         String message = in.read_string ();
         String $result = null;
         $result = this.connect (message);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // repository/LibraryInterface/addItem
       {
         String managerID = in.read_string ();
         String itemID = in.read_string ();
         String itemName = in.read_string ();
         int quantity = in.read_long ();
         String $result = null;
         $result = this.addItem (managerID, itemID, itemName, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // repository/LibraryInterface/removeItem
       {
         String managerID = in.read_string ();
         String itemID = in.read_string ();
         int quantity = in.read_long ();
         String $result = null;
         $result = this.removeItem (managerID, itemID, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // repository/LibraryInterface/listItemAvailability
       {
         String managerID = in.read_string ();
         String $result = null;
         $result = this.listItemAvailability (managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // repository/LibraryInterface/borrowItem
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         String $result = null;
         $result = this.borrowItem (userID, itemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // repository/LibraryInterface/findItem
       {
         String userID = in.read_string ();
         String itemName = in.read_string ();
         String $result = null;
         $result = this.findItem (userID, itemName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // repository/LibraryInterface/returnItem
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         String $result = null;
         $result = this.returnItem (userID, itemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // repository/LibraryInterface/exchangeItem
       {
         String userID = in.read_string ();
         String newItemID = in.read_string ();
         String oldItemID = in.read_string ();
         String $result = null;
         $result = this.exchangeItem (userID, newItemID, oldItemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // repository/LibraryInterface/oldBookCheck
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         String $result = null;
         $result = this.oldBookCheck (userID, itemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // repository/LibraryInterface/newBookCheck
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         String $result = null;
         $result = this.newBookCheck (userID, itemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 10:  // repository/LibraryInterface/addToWaitlist
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         String $result = null;
         $result = this.addToWaitlist (userID, itemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 11:  // repository/LibraryInterface/serverRequestFind
       {
         String userID = in.read_string ();
         String itemName = in.read_string ();
         String $result = null;
         $result = this.serverRequestFind (userID, itemName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 12:  // repository/LibraryInterface/checkBorrowedBooks
       {
         String userID = in.read_string ();
         int $result = (int)0;
         $result = this.checkBorrowedBooks (userID);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:repository/LibraryInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public LibraryInterface _this() 
  {
    return LibraryInterfaceHelper.narrow(
    super._this_object());
  }

  public LibraryInterface _this(org.omg.CORBA.ORB orb) 
  {
    return LibraryInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class LibraryInterfacePOA
