package repository;


/**
* repository/LibraryInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LibraryInterface.idl
* Friday, 22 March, 2019 10:53:02 PM EDT
*/

abstract public class LibraryInterfaceHelper
{
  private static String  _id = "IDL:repository/LibraryInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, repository.LibraryInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static repository.LibraryInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (repository.LibraryInterfaceHelper.id (), "LibraryInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static repository.LibraryInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LibraryInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, repository.LibraryInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static repository.LibraryInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof repository.LibraryInterface)
      return (repository.LibraryInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      repository._LibraryInterfaceStub stub = new repository._LibraryInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static repository.LibraryInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof repository.LibraryInterface)
      return (repository.LibraryInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      repository._LibraryInterfaceStub stub = new repository._LibraryInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
