package server.interfaces;

public enum LibraryOperationsEnum {
	USER_EXISTS, ADD_ITEM, REMOVE_ITEM, LIST_AVAILABLE_ITEM, BORROW_ITEM, FIND_ITEM, RETURN_ITEM, ADD_TO_WAITING_LIST, ADD_TO_WAITING_LIST_OVERLOADED, EXCHANGE_ITEM;
}
